### ISSUE TITLE
Bug adding hosts to host file

### ISSUE THREAD

**Issue by Saturate** [feross/hostile#13] opened 2015-03-06 08:02 UTC
Hello,

I'm trying to add some host like this:

```
project.hosts.forEach(function (mapping) {
	hostile.set(mapping.ip, mapping.hostname, function (err) {
		if (err) {
			console.error(err)
		} else {
			console.log('Successfully added:', mapping.ip, mapping.hostname);
		}
	});
});
```

It outputs:

```
[09:01:27] Starting 'apply-hosts'...
Successfully added: 127.0.0.1 brian.example.com
Successfully added: 127.0.0.1 allan.example.com
```

but only `brian.example.com`is added to the host file. I'm running windows 8.1.

**Comment by feross** [comment] 2015-03-06 21:41
Duplicate of #9.

**Closed by feross** 2015-03-06 21:41 UTC
